/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  11155111: {
    EvalMarket: {
      address: "0x3712e8d0196e7266b44f62695189b3580f6fd2c1",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "purchaseId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "buyerWon",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "address",
              name: "disputeBondRecipient",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "disputeBondAmount",
              type: "uint256",
            },
          ],
          name: "DisputeResolved",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "purchaseId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "disputer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "reproductionHash",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "disputeBond",
              type: "uint256",
            },
          ],
          name: "Disputed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "listingId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "seller",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "modelName",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "modelVersionId",
              type: "string",
            },
            {
              indexed: false,
              internalType: "enum EvalMarket.EvalCategory",
              name: "evalCategory",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "reportHash",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "methodologyHash",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "validUntil",
              type: "uint256",
            },
          ],
          name: "ListingCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "listingId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "newValidUntil",
              type: "uint256",
            },
          ],
          name: "ListingValidityExtended",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "listingId",
              type: "uint256",
            },
          ],
          name: "ListingWithdrawn",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "purchaseId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "listingId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "buyer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amountPaid",
              type: "uint256",
            },
          ],
          name: "Purchased",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "purchaseId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "Released",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "purchaseId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "reportURI",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "methodologyURI",
              type: "string",
            },
          ],
          name: "Revealed",
          type: "event",
        },
        {
          inputs: [],
          name: "CHALLENGE_WINDOW",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "DISPUTE_BOND",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "MIN_BOND",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "arbiter",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "modelName",
              type: "string",
            },
            {
              internalType: "string",
              name: "modelVersionId",
              type: "string",
            },
            {
              internalType: "enum EvalMarket.EvalCategory",
              name: "evalCategory",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
            {
              internalType: "bytes32",
              name: "reportHash",
              type: "bytes32",
            },
            {
              internalType: "bytes32",
              name: "methodologyHash",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "validUntil",
              type: "uint256",
            },
          ],
          name: "createListing",
          outputs: [
            {
              internalType: "uint256",
              name: "listingId",
              type: "uint256",
            },
          ],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "purchaseId",
              type: "uint256",
            },
            {
              internalType: "bytes32",
              name: "reproductionHash",
              type: "bytes32",
            },
          ],
          name: "dispute",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "listingId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "newValidUntil",
              type: "uint256",
            },
          ],
          name: "extendValidity",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "seller",
              type: "address",
            },
          ],
          name: "getReputation",
          outputs: [
            {
              internalType: "uint256",
              name: "successfulSales",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "disputesLost",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "listings",
          outputs: [
            {
              internalType: "address payable",
              name: "seller",
              type: "address",
            },
            {
              internalType: "string",
              name: "modelName",
              type: "string",
            },
            {
              internalType: "string",
              name: "modelVersionId",
              type: "string",
            },
            {
              internalType: "enum EvalMarket.EvalCategory",
              name: "evalCategory",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
            {
              internalType: "bytes32",
              name: "reportHash",
              type: "bytes32",
            },
            {
              internalType: "bytes32",
              name: "methodologyHash",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "bond",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "validUntil",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "active",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "listingsCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "listingId",
              type: "uint256",
            },
          ],
          name: "purchase",
          outputs: [
            {
              internalType: "uint256",
              name: "purchaseId",
              type: "uint256",
            },
          ],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "purchases",
          outputs: [
            {
              internalType: "uint256",
              name: "listingId",
              type: "uint256",
            },
            {
              internalType: "address payable",
              name: "buyer",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "amountPaid",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "reportURI",
              type: "string",
            },
            {
              internalType: "string",
              name: "methodologyURI",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "revealTimestamp",
              type: "uint256",
            },
            {
              internalType: "enum EvalMarket.PurchaseState",
              name: "state",
              type: "uint8",
            },
            {
              internalType: "address",
              name: "disputer",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "disputeBond",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "purchasesCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "purchaseId",
              type: "uint256",
            },
          ],
          name: "releaseIfUnchallenged",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "reputationOf",
          outputs: [
            {
              internalType: "uint256",
              name: "successfulSales",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "disputesLost",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "purchaseId",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "buyerWins",
              type: "bool",
            },
          ],
          name: "resolveDispute",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "purchaseId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "reportURI",
              type: "string",
            },
            {
              internalType: "string",
              name: "methodologyURI",
              type: "string",
            },
          ],
          name: "reveal",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "listingId",
              type: "uint256",
            },
          ],
          name: "withdrawListing",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 11683978,
    },
    YourContract: {
      address: "0xe783d428f8430b7d3ee32470f8df8d05e98333d1",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_owner",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "greetingSetter",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "newGreeting",
              type: "string",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "premium",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "GreetingChange",
          type: "event",
        },
        {
          inputs: [],
          name: "greeting",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "premium",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_newGreeting",
              type: "string",
            },
          ],
          name: "setGreeting",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "totalCounter",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "userGreetingCounter",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "withdraw",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 11681464,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
